name: Python package

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.14"]

        steps:
            - uses: actions/checkout@v7
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install PDM
              uses: pdm-project/setup-pdm@v4
              with:
                  cache: true
                  cache-dependency-path: pdm.lock
            - name: Install dependencies
              run: |
                  pdm install --group dev
                  pdm run playwright install --with-deps chromium
            - name: Lint with ruff
              run: |
                  pdm run lint
            - name: Test with pytest
              run: |
                  pdm run test
